[package]
authors = ["Paul Collier <paul@paulcollier.ca>"]
name = "dag"
version = "0.1.0"

[dependencies]
bincode = "0.8.0"
bytes = "0.4.4"
digest = "0.6.1"
error-chain = "0.10.0"
serde = "1.0.8"
serde_derive = "1.0.8"
sha3 = "0.6.0"

[dev-dependencies]
tempdir = "0.3.5"
tempfile = "2.1.5"
