[package]
authors = ["Paul Collier <paul@paulcollier.ca>"]
name = "server"
publish = false
version = "0.1.0"

[dependencies]
futures = "0.1"
proto = { path = "../proto" }
serde = "0.9"
tokio-core = "0.1"
tokio-io = "0.1"
