[package]
authors = ["Paul Collier <paul@paulcollier.ca>"]
name = "proto"
version = "0.1.0"

[dependencies]
bytes = "0.4.4"
serde_derive = "1.0.7"

[dependencies.dag]
path = "../dag"

[dependencies.serde]
features = ["rc"]
version = "1.0.7"
