[package]
authors = ["Paul Collier <paul@paulcollier.ca>"]
name = "proto"
version = "0.1.0"

[dependencies]
bincode = "0.8.0"
bytes = "0.4.4"
serde_derive = "1.0.7"

[dependencies.serde]
features = ["rc"]
version = "1.0.7"

[dev-dependencies]
tempfile = "2.1.5"
