[package]
authors = ["Paul Collier <paul@paulcollier.ca>"]
name = "driver"
version = "0.1.0"

[dependencies]
libc = "0.2"
serde = "0.9"

[dependencies.proto]
path = "../proto"

[lib]
crate-type = ["dylib"]
name = "driver"
