[package]
authors = ["Paul Collier <paul@paulcollier.ca>"]
name = "issuer"
publish = false
version = "0.1.0"

[dependencies]
digest = "0.5"
proto = { path = "../proto" }
rpassword = "0.4.0"
sha3 = "0.5.0"
sodiumoxide = "0.0.14"
