[package]
authors = ["Paul Collier <paul@paulcollier.ca>"]
name = "issuer"
publish = false
version = "0.1.0"

[dependencies]
digest = "0.6"
error-chain = "0.10.0"
rpassword = "0.4.0"
sha3 = "0.6"
sodiumoxide = "0.0.15"

[dependencies.proto]
path = "../proto"
