[package]
authors = ["Paul Collier <paul@paulcollier.ca>"]
name = "g"
version = "0.1.0"

[dependencies]
gfx = "0.14.0"
gfx_device_gl = "0.13"
gfx_text = "0.15.0"
gfx_window_glutin = "0.14"
glutin = "0.7.4"

[lib]
crate-type = ["dylib"]
name = "g"
